[[Xorg_kbproto]]
arch = "armv7l"
git-tree-sha1 = "841f339a9c991261007d444a5dbb1b07e71096f9"
libc = "glibc"
os = "linux"

    [[Xorg_kbproto.download]]
    sha256 = "86df85fccb0b42eae4e24e259a92cbafaf252ff14b47225c93388240afca537c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_kbproto_jll.jl/releases/download/Xorg_kbproto-v1.0.7+1/Xorg_kbproto.v1.0.7.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_kbproto]]
arch = "i686"
git-tree-sha1 = "520aeb4f6e55aef5b1bebbbb18a30e512569c30b"
libc = "musl"
os = "linux"

    [[Xorg_kbproto.download]]
    sha256 = "2f5ac7bede861c7d9bfb9baee8ddc98477f7f54c0632ed0fd0190cd99393e77b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_kbproto_jll.jl/releases/download/Xorg_kbproto-v1.0.7+1/Xorg_kbproto.v1.0.7.i686-linux-musl.tar.gz"
[[Xorg_kbproto]]
arch = "aarch64"
git-tree-sha1 = "8ae88876cbc62313b209428e8d3842d989e38778"
libc = "glibc"
os = "linux"

    [[Xorg_kbproto.download]]
    sha256 = "5363f864a22c06f46d24341626f5ca0bafb9f5c3aae10e5c1c8b378d4b0b1e9f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_kbproto_jll.jl/releases/download/Xorg_kbproto-v1.0.7+1/Xorg_kbproto.v1.0.7.aarch64-linux-gnu.tar.gz"
[[Xorg_kbproto]]
arch = "armv7l"
git-tree-sha1 = "b9cba74c9d984e85390ec98f3b5523db45899f78"
libc = "musl"
os = "linux"

    [[Xorg_kbproto.download]]
    sha256 = "c5b29bed8de830526bb8575385c575d617033b11afc73adb27314b4752aba482"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_kbproto_jll.jl/releases/download/Xorg_kbproto-v1.0.7+1/Xorg_kbproto.v1.0.7.armv7l-linux-musleabihf.tar.gz"
[[Xorg_kbproto]]
arch = "aarch64"
git-tree-sha1 = "db802b5a576ed0b4302020ba69132522a084c06d"
libc = "musl"
os = "linux"

    [[Xorg_kbproto.download]]
    sha256 = "c6b99e8d096d02d023922695fe5135d1eb044670f055c3a4bc6a6ecdc9a1639d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_kbproto_jll.jl/releases/download/Xorg_kbproto-v1.0.7+1/Xorg_kbproto.v1.0.7.aarch64-linux-musl.tar.gz"
[[Xorg_kbproto]]
arch = "x86_64"
git-tree-sha1 = "e80fa03f34363f4cb59af63577e90895692639f4"
os = "freebsd"

    [[Xorg_kbproto.download]]
    sha256 = "d4f3ea88269705d5c79943e4bd6626e7b8aaf4accb9fd843cf462376b7581989"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_kbproto_jll.jl/releases/download/Xorg_kbproto-v1.0.7+1/Xorg_kbproto.v1.0.7.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_kbproto]]
arch = "i686"
git-tree-sha1 = "696fa5e008813a4a176f4d45b3e517f54b17d2ff"
libc = "glibc"
os = "linux"

    [[Xorg_kbproto.download]]
    sha256 = "51e6cac7a8a186594c3793448c3a8a3b0e5ccb888a6f2b39da6f744f0e5f2828"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_kbproto_jll.jl/releases/download/Xorg_kbproto-v1.0.7+1/Xorg_kbproto.v1.0.7.i686-linux-gnu.tar.gz"
[[Xorg_kbproto]]
arch = "x86_64"
git-tree-sha1 = "dd64091e5edc4b8d9ef79226f2eb00ee0329067b"
libc = "musl"
os = "linux"

    [[Xorg_kbproto.download]]
    sha256 = "b63cfefe2cc32c674d0892c7e91ff7f7958174fc80384d7e19e6085764d79b85"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_kbproto_jll.jl/releases/download/Xorg_kbproto-v1.0.7+1/Xorg_kbproto.v1.0.7.x86_64-linux-musl.tar.gz"
[[Xorg_kbproto]]
arch = "x86_64"
git-tree-sha1 = "beea8a36db6a884f320d64940772dccfb26f7950"
libc = "glibc"
os = "linux"

    [[Xorg_kbproto.download]]
    sha256 = "a3ba0d80595381206e8b1374927fbe9ef537bef21708ee91d718a8a3406ca907"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_kbproto_jll.jl/releases/download/Xorg_kbproto-v1.0.7+1/Xorg_kbproto.v1.0.7.x86_64-linux-gnu.tar.gz"
[[Xorg_kbproto]]
arch = "powerpc64le"
git-tree-sha1 = "aa08e64aac672bbb0879e0f96e0071a8bc701de0"
libc = "glibc"
os = "linux"

    [[Xorg_kbproto.download]]
    sha256 = "b1aab2f1559b875d3758f2643d0591f640524900284faa23f04e554d5c214ae6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_kbproto_jll.jl/releases/download/Xorg_kbproto-v1.0.7+1/Xorg_kbproto.v1.0.7.powerpc64le-linux-gnu.tar.gz"
